#!/bin/sh
#/etc/init.d/capsuleDjangoService

### BEGIN INIT INFO
# Provides: capsuleDjangoService
# Required-Start:		$remote_fs $syslog $time
# Required-Stop:		$remote_fs $syslog $time
# Default-Start:		2 3 4 5
# Default-Stop:			0 1 6
# Short-Description:	capsule django server
### END INIT INFO

case "$1" in
start)
#source /home/pi/workspace/django_venv/bin/activate
python3 /opt/capsuleFW_react/backend/manage.py runserver 0.0.0.0:8000
;;
stop)
echo "capsuleDjangoService stop"
;;
*)
echo "Usage: /etc/init.d/capsuleDjangoService"
exit 1
;;
esac
exit 0
